#!/usr/bin/env bash
# Create a new migration file with a collision-free id.
#
#   ./new_migration.sh add_evidence_profile_columns
#
# The id is a UTC timestamp, not the next number. Nobody has to look at what
# anyone else picked, which is the only property that survives two sessions
# authoring at the same time. See ./migrate.sh, "The ordering rule".
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
slug="${1:-}"
[[ -z $slug ]] && { echo "usage: $0 <lower_snake_slug>" >&2; exit 1; }
[[ $slug =~ ^[a-z0-9_]+$ ]] || { echo "slug must be [a-z0-9_]+" >&2; exit 1; }

id="$(date -u +%Y%m%dT%H%M%SZ)"
# Same-second collision inside one machine is the only case a timestamp does
# not cover on its own.
while [[ -e "$HERE/migrations/${id}__${slug}.sql" ]] || compgen -G "$HERE/migrations/${id}__*.sql" > /dev/null; do
    sleep 1; id="$(date -u +%Y%m%dT%H%M%SZ)"
done

f="$HERE/migrations/${id}__${slug}.sql"
cat > "$f" <<EOF
-- ---------------------------------------------------------------------------
-- ${id}__${slug}.sql   (ticket NN)
--
-- Applied by ./migrate.sh in one transaction with its schema_migrations row.
--
-- Rules this file has to keep, all of them checked by ./migrate.sh up:
--   * every new table gets an event_table_config row (it emits) or an
--     event_table_exempt row (it does not, with a reason). Neither is a
--     failure, not a default -- check_event_coverage() will refuse the run.
--   * do NOT call attach_event_triggers(); the runner does it after every
--     migration has applied, which is what makes ordering between migrations
--     stop mattering. Call it only if this file INSERTs into a table it just
--     created and wants the events for those rows.
--   * do not edit this file once it has been applied anywhere: the checksum in
--     schema_migrations will refuse the next run.
-- ---------------------------------------------------------------------------

EOF
echo "$f"
