-- ---------------------------------------------------------------------------
-- 20260928T010000Z__a_step_mints_its_own_correlator.sql
--                                                                   (ticket 98)
--
-- Ticket 14 built the record and ticket 69 built the channel, and between them
-- they left the out-of-band capability sound and unreachable: the only way to
-- mint a correlator is `rk callback provision`, which is an operator standing
-- at a terminal. Two Playbooks already tell a step to get one -- `webhooks`
-- step 1 says "ask the runtime for a correlator for this subject" -- and there
-- has never been anything to ask. This file is the thing to ask.
--
-- WHY A VERB RATHER THAN THE SUPERVISOR CALLING `mint_callback_correlator`.
--
-- Because minting is the smallest part of it. What a correlator needs before
-- it can be minted is the live scope version, the channel that version
-- declares, the live binding under that channel's name, the Entity the canary
-- is about, and the Tool run whose egress will carry the name out -- five
-- lookups, each of which is a refusal a child should be told about in words.
-- Written in the supervisor that is five round trips and five sentences in a
-- second language; written here it is one statement beside the table whose
-- constraints it is anticipating, and `mint_callback_correlator` is left doing
-- exactly what it did before.
--
-- WHAT THE MODEL DOES NOT DECIDE, AND WHY EACH ONE.
--
-- The correlator: it is generated by the supervisor with `secrets.token_hex`
-- and arrives here already made, so a child cannot choose a name that collides
-- with one it planted earlier or one it read somewhere. The lifetime: it is
-- written below and takes no argument, because a correlator planted in a
-- target's system is a durable artefact whose life we do not control and the
-- one thing we can control is when it stops attributing. And the channel: a
-- Program declares its channels in scope policy, and this verb mints only when
-- there is exactly one to mint on -- naming it, so that a child that believes
-- it is planting on some other name is told it is wrong rather than quietly
-- given the row-order winner. `program_callback_channels` refuses two channels
-- on one host for that same reason.
--
-- It is INVOKER. The caller is `rk2_runtime`, which already executes both
-- functions this one calls and already reads all five relations it looks in; a
-- definer wrapper would hand the runtime a privilege it does not need to do
-- what it can already do.


-- ===========================================================================
-- 1. The caller's half of `mint_callback_correlator`
-- ===========================================================================

--: How long an agent-minted correlator attributes for. An hour, which is what
--: `callback.DEFAULT_LIFETIME` gives an operator who does not say -- but it is
--: written here rather than passed in, because on this path there is no
--: operator to say. A number a child could name would be the one limit on a
--: durable artefact handed to the party with the least reason to keep it short.
CREATE FUNCTION request_callback_correlator(
        p_channel    text,
        p_correlator text,
        p_subject    text,
        p_agent_run  uuid DEFAULT NULL)
RETURNS jsonb
LANGUAGE plpgsql AS $fn$
DECLARE
    p          uuid := rk2_program_required();
    v_channel  text := btrim(coalesce(p_channel, ''));
    v_said     text := btrim(coalesce(p_subject, ''));
    v_version  integer;
    v_declared text[];
    v_entity   uuid;
    v_tool_run uuid;
    v_binding  jsonb;
    v_id       uuid;
    v_expires  timestamptz;
BEGIN
    -- The provenance guard first, in `propose_finding`'s words and for its
    -- reason: an Agent run belonging to another Program is not a run this
    -- correlator may be attributed to, and the composite foreign key on
    -- `callback_correlators` would raise on the Tool run resolved from it.
    IF NOT EXISTS (
        SELECT 1 FROM agent_runs ar WHERE ar.id = p_agent_run AND ar.program_id = p
    ) THEN
        RETURN jsonb_build_object('outcome', 'refused', 'refusal',
            'the Agent run asking for this correlator is not a run of this Program');
    END IF;

    SELECT pr.scope_version INTO v_version
      FROM programs pr WHERE pr.id = p AND pr.closed_at IS NULL;
    IF NOT FOUND THEN
        RETURN jsonb_build_object('outcome', 'refused', 'refusal',
            'this Program is closed, so no new correlator may be minted for it');
    END IF;

    -- One channel per Program, checked as a count and reported as one. The
    -- scope compiler admits several and `mint_callback_correlator` would take
    -- any of them; what this verb will not do is pick. A model that is told
    -- "there are two, they are these" can say which; a model handed the first
    -- row has planted a name it did not choose in somebody else's system.
    SELECT array_agg(c.name ORDER BY c.name) INTO v_declared
      FROM program_callback_channels c
     WHERE c.program_id = p AND c.version = v_version;
    IF v_declared IS NULL THEN
        RETURN jsonb_build_object('outcome', 'refused', 'refusal',
            'this Program declares no out-of-band channel, so there is no name to plant');
    END IF;
    IF array_length(v_declared, 1) <> 1 THEN
        RETURN jsonb_build_object('outcome', 'refused', 'refusal',
            format('this Program declares %s out-of-band channels (%s) and a step mints on one',
                   array_length(v_declared, 1), array_to_string(v_declared, ', ')));
    END IF;
    IF v_declared[1] IS DISTINCT FROM v_channel THEN
        RETURN jsonb_build_object('outcome', 'refused', 'refusal',
            format('%s is not this Program''s out-of-band channel; it declares %s',
                   coalesce(nullif(v_channel, ''), '(none)'), v_declared[1]));
    END IF;

    SELECT e.id INTO v_entity
      FROM entities e WHERE e.program_id = p AND e.label = v_said;
    IF v_entity IS NULL THEN
        RETURN jsonb_build_object('outcome', 'refused', 'refusal',
            format('%s is not an Entity of this Program, and a correlator has a subject '
                   'because the Observation it produces has one',
                   coalesce(nullif(v_said, ''), '(none)')));
    END IF;

    -- The run that will plant it. `callback_correlators` binds to a Tool run or
    -- a Test run and to neither an Agent run nor a Task, so the narrowest true
    -- binding available for a child is the egress Tool run its own requests go
    -- out on -- the one `execution._authorize` opened for this attempt, which
    -- is also the run every Receipt for the planting request will hang off.
    --
    -- The literal is the tool name the RUNTIME opens the run under, which is
    -- not the name the model calls the door by. Ticket 97 recorded that hazard
    -- in `roster.py` above the served name; this is the other end of it, and a
    -- ticket that changed which name a Tool run is opened under would have to
    -- change this line with it.
    SELECT tr.id INTO v_tool_run
      FROM tool_runs tr
     WHERE tr.program_id = p AND tr.agent_run_id = p_agent_run
       AND tr.tool = 'mcp__rk2__net_request'
     ORDER BY tr.started_at DESC
     LIMIT 1;
    IF v_tool_run IS NULL THEN
        RETURN jsonb_build_object('outcome', 'refused', 'refusal',
            'this run has no egress Tool run, so it has no way to carry a correlator out');
    END IF;

    -- Where the channel is answering, asked of the database and not of any
    -- configuration this process read: a bound channel answers at whatever
    -- `rk oob up` last bound, and a name composed from a stale binding is a
    -- canary nothing can reach.
    v_binding := callback_channel_binding(v_channel);
    IF NOT coalesce((v_binding ->> 'bound')::boolean, false) THEN
        RETURN jsonb_build_object('outcome', 'refused', 'refusal',
            format('channel %s has no live binding, so there is no name to embed; '
                   '`rk oob up` binds one', v_channel));
    END IF;

    -- Every refusal `mint_callback_correlator` can raise is about the same five
    -- things this function has just checked, so reaching one of them means the
    -- two disagree. It is still answered rather than raised: a child holding a
    -- tool that failed learns nothing, and a child holding the sentence can
    -- report it.
    BEGIN
        v_id := mint_callback_correlator(
            v_channel, p_correlator, v_entity, interval '1 hour', v_tool_run, NULL);
    EXCEPTION WHEN OTHERS THEN
        RETURN jsonb_build_object('outcome', 'refused', 'refusal', SQLERRM);
    END;

    SELECT cc.expires_at INTO v_expires
      FROM callback_correlators cc WHERE cc.id = v_id;

    RETURN jsonb_build_object(
        'outcome', 'minted',
        'correlator_id', v_id::text,
        -- The one string a step embeds, composed by the rule `callback._address`
        -- states for the operator path: a label channel is addressed by name,
        -- because a DNS query carries no path, and a path channel is one bound
        -- host serving every canary of a Program under its own first segment.
        -- Two copies of one rule, and the assertion in section 2 is what holds
        -- them together; a later ticket that gave `rk callback provision` this
        -- verb to call would leave one.
        'address', CASE WHEN v_binding ->> 'placement' = 'path'
                        THEN 'https://' || (v_binding ->> 'endpoint') || '/' || p_correlator || '/'
                        ELSE p_correlator || '.' || (v_binding ->> 'endpoint') END,
        'channel', v_channel,
        'kind', v_binding ->> 'kind',
        'placement', v_binding ->> 'placement',
        'subject_label', v_said,
        'expires_at', v_expires::text);
END $fn$;

COMMENT ON FUNCTION request_callback_correlator(text, text, text, uuid) IS
    'Ticket 98. The agent-facing half of `mint_callback_correlator`: a channel '
    'name and an Entity label a child can read, resolved to the live scope '
    'version, the Program''s one declared channel, its live binding, the '
    'subject Entity and the egress Tool run that will carry the name out. '
    'Answers the address to embed and the correlator id, or a refusal in words. '
    'The correlator itself is minted by the caller and the lifetime is fixed '
    'here, because neither is the model''s to choose.';

REVOKE ALL ON FUNCTION request_callback_correlator(text, text, text, uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION request_callback_correlator(text, text, text, uuid) TO rk2_runtime;

-- 066's registry. `check_runtime_privileges` refuses a verb the runtime can
-- execute that no row here names, so the grant above and this row are one
-- statement made twice on purpose: the second half is the one a reader of the
-- surface finds.
INSERT INTO runtime_verb_surface (verb, added_by, note) VALUES
    ('request_callback_correlator(text, text, text, uuid)',
     '98',
     'resolves a channel name and an Entity label to the rows a correlator rests on and calls mint_callback_correlator -- the agent-facing half of a capability that until this ticket only `rk callback provision` could reach');


-- ===========================================================================
-- 2. What this migration claims, asserted
-- ===========================================================================

DO $$
DECLARE v_address text;
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_proc
         WHERE proname = 'request_callback_correlator'
           AND has_function_privilege('rk2_runtime', oid, 'EXECUTE')
    ) THEN
        RAISE EXCEPTION 'ticket 98: the runtime cannot ask for a correlator';
    END IF;

    -- The point of the whole ticket, stated as the thing that would have to
    -- stay true. The verb above is reachable only because the runtime may also
    -- execute the two functions it calls, so a later file that dropped either
    -- grant should fail here rather than quietly return the capability to the
    -- state ticket 98 found it in: sound, and reachable by nobody but an
    -- operator at a terminal.
    IF NOT EXISTS (
        SELECT 1 FROM pg_proc
         WHERE proname = 'mint_callback_correlator'
           AND has_function_privilege('rk2_runtime', oid, 'EXECUTE')
    ) THEN
        RAISE EXCEPTION 'ticket 98: mint_callback_correlator is not executable by its caller';
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_proc
         WHERE proname = 'callback_channel_binding'
           AND has_function_privilege('rk2_runtime', oid, 'EXECUTE')
    ) THEN
        RAISE EXCEPTION 'ticket 98: callback_channel_binding is not executable by its caller';
    END IF;

    -- The composition above branches on `placement` and has two arms, so it is
    -- only total while `placement` has two values. A third one -- added to the
    -- channel vocabulary by some later ticket -- would fall into the ELSE and
    -- publish a DNS-shaped name for a channel that is not one, which is a
    -- canary the listener will never admit and nothing else would notice. This
    -- is the assertion the two-copy comment above names: it does not prove the
    -- SQL and `callback._address` agree, it proves the question they both
    -- answer still has the two answers they were written for.
    SELECT pg_get_constraintdef(oid) INTO v_address
      FROM pg_constraint
     WHERE conrelid = 'program_callback_channels'::regclass
       AND contype = 'c' AND pg_get_constraintdef(oid) LIKE '%placement%'
       AND pg_get_constraintdef(oid) LIKE '%ANY%';
    IF v_address IS NULL OR v_address NOT LIKE '%''label''%' OR v_address NOT LIKE '%''path''%'
       OR v_address LIKE '%,%,%' THEN
        RAISE EXCEPTION 'ticket 98: a channel placement is no longer exactly label or path'
          USING DETAIL = coalesce(v_address, 'no check constraint names placement');
    END IF;

    -- And the binding this verb chooses. `callback_correlators` admits a Tool
    -- run or a Test run and never both, and the column this file writes is the
    -- first; a corpus that dropped it would leave the verb attributing an
    -- arrival to nothing.
    IF NOT EXISTS (
        SELECT 1 FROM pg_attribute
         WHERE attrelid = 'callback_correlators'::regclass
           AND attname = 'tool_run_id' AND NOT attisdropped
    ) THEN
        RAISE EXCEPTION 'ticket 98: a correlator can no longer name the run that planted it';
    END IF;
END $$;
