#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
#
# Ticket 146. The one step a human has to take, and the four checks around it.
# `claude setup-token` is an interactive browser flow that only the operator can
# complete, and what it prints is a live Anthropic credential — so this script
# reads it once, hidden, installs it as a `0600` file nobody else on this
# machine can open, and never writes it anywhere else.
#
# Two library helpers are deliberately unused. `write_env` would put the token
# in a `.env` file beside a checkout, and `set_secret` would put it in a CI
# provider; the whole point of the file below is that neither happens. `ENV_FILE`
# is pointed at nothing so that a stray `.env` in the working directory cannot
# be read as a default either.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

ENV_FILE=/dev/null

TOKEN_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/redkraken"
TOKEN_FILE="${RK_AGENT_OAUTH_TOKEN_FILE:-$TOKEN_DIR/claude-oauth-token}"
REPO_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"

if [[ "$TOKEN_FILE" != /* ]]; then
  warn "RK_AGENT_OAUTH_TOKEN_FILE has to name an absolute path: $TOKEN_FILE"
  exit 1
fi

banner "redKraken — the Agent's Claude setup token"

# ── 1. Which CLI is about to mint the token ───────────────────────────────
stage "The CLI that mints it"
say "A setup token is minted by the Claude CLI on this machine, and it is that"
say "CLI's login it carries. So the first thing to be sure of is which one runs."
if ! command -v claude >/dev/null 2>&1; then
  warn "no \`claude\` on PATH — install the Claude CLI and re-run this script"
  exit 1
fi
AMBIENT_CLI="$(command -v claude)"
AMBIENT_VERSION="$(claude --version 2>/dev/null | head -n1 || echo 'unknown')"
say "This wizard will run: $AMBIENT_CLI"
say "It reports: $AMBIENT_VERSION"
note "That is the ambient CLI, and it is not the one an Agent run uses. A child"
note "runs the SDK and CLI the harness bundles into its own image, and the"
note "startup assertion measures that pair rather than this one. A setup token"
note "is a credential and not a build, so a token minted here is the token the"
note "bundled pair presents — which is what stage 5 goes and checks."
if ! confirm "Mint a setup token with $AMBIENT_CLI?"; then
  warn "nothing was changed"
  exit 1
fi

# ── 2. The one human step ─────────────────────────────────────────────────
stage "claude setup-token"
say "Running \`claude setup-token\`. It opens a browser, asks you to authorise,"
say "and prints the token when you come back. Copy it — the next prompt is"
say "hidden, so nothing this script does puts it on your screen again."
printf '\n'
claude setup-token || { warn "\`claude setup-token\` did not complete"; exit 1; }
printf '\n'
pause "Copied the token?"

# ── 3. Install it atomically, readable by this operator alone ─────────────
stage "Install the token"
ask_secret RK_SETUP_TOKEN "Paste the setup token (hidden):"
if [[ -z "$RK_SETUP_TOKEN" ]]; then
  warn "nothing was pasted; the token was not installed"
  exit 1
fi
case "$RK_SETUP_TOKEN" in
  *[[:space:]]*) warn "that value carries whitespace and a setup token is one word"; exit 1 ;;
esac

mkdir -p -- "$(dirname -- "$TOKEN_FILE")"
chmod 0700 -- "$(dirname -- "$TOKEN_FILE")"
# Written through a temporary file in the same directory and renamed over the
# target, so a reader either sees the old token or the new one and never a
# half-written file. `umask` first, because a file created wide and narrowed
# afterwards is a file that was readable for as long as the chmod took.
INSTALL_TMP="$(umask 077 && mktemp -- "$(dirname -- "$TOKEN_FILE")/.token.XXXXXX")"
trap 'rm -f -- "$INSTALL_TMP"' EXIT
printf '%s\n' "$RK_SETUP_TOKEN" > "$INSTALL_TMP"
chmod 0600 -- "$INSTALL_TMP"
mv -f -- "$INSTALL_TMP" "$TOKEN_FILE"
trap - EXIT
unset RK_SETUP_TOKEN
say "Installed at $TOKEN_FILE"
ls -l -- "$TOKEN_FILE" | sed 's/^/  /'
note "0600, owned by you, one line. Anything else and the runtime refuses it"
note "rather than handing it to a child."
note "An existing ~/.claude/.credentials.json is left exactly where it is. The"
note "harness has stopped reading it; it is yours to keep or remove."

# ── 4. Ask the doctor, which is what a run asks before it spends an attempt ─
stage "rk doctor"
say "The doctor asks the same question a launch asks, before a Task pays for the"
say "answer. Its \`agent_credential\` assertion is the one this script is about."
if command -v rk >/dev/null 2>&1; then
  RK=(rk)
else
  RK=(python3 -m redkraken)
  note "no \`rk\` on PATH; using \`python3 -m redkraken\` from $REPO_ROOT"
fi
DOCTOR_REPORT="$(mktemp)"
trap 'rm -f -- "$DOCTOR_REPORT"' EXIT
if (cd "$REPO_ROOT" && "${RK[@]}" doctor) > "$DOCTOR_REPORT" 2>&1; then
  say "the doctor holds"
else
  warn "the doctor refused — read the violations below"
fi
python3 - "$DOCTOR_REPORT" <<'DOCTOR' || true
import json, sys
try:
    report = json.load(open(sys.argv[1]))
except Exception:
    print("  the doctor produced no report; run `rk doctor` by hand")
    raise SystemExit(0)
for assertion in report.get("assertions", ()):
    if assertion["name"] == "agent_credential":
        print(f"  agent_credential: {'holds' if assertion['ok'] else 'REFUSED'}")
        print(f"    {assertion['detail']}")
for violation in report.get("violations", ()):
    print(f"  violation {violation['code']} at {violation['source']}")
    print(f"    {violation['detail']}")
DOCTOR
rm -f -- "$DOCTOR_REPORT"
trap - EXIT

# ── 5. One contained child, with the pair the harness bundles ─────────────
stage "The canary"
say "One Agent run, in a real boundary, with the SDK and CLI the harness ships."
say "What it proves is the only thing a file on disk cannot: that the bundled"
say "pair authenticates with this token and reports no API key behind it."
if [[ -z "${RK_AGENT_IMAGE:-}" || -z "${RK_AGENT_NETWORK:-}" ]]; then
  warn "no Agent boundary is exported in this shell (RK_AGENT_IMAGE, RK_AGENT_NETWORK, ...)"
  SKIPPED+=("the canary — export the RK_AGENT_* boundary and re-run this stage")
elif confirm "Start one contained Agent run now?"; then
  (cd "$REPO_ROOT" && python3 - <<'CANARY') || SKIPPED+=("the canary — it did not report apiKeySource=none")
import os
import sys

sys.path.insert(0, "src")
from redkraken import agent, execution, isolation

container, missing = execution.boundary(os.environ)
if container is None:
    print("  the Agent boundary is described only in part: " + ", ".join(missing))
    raise SystemExit(1)
if isolation.oauth_token() is None:
    print("  no setup token was readable; the install above did not take")
    raise SystemExit(1)

answer = agent.agent_run(
    agent.AgentRunRequest(
        agent_run_id="00000000-0000-4000-8000-0000000000ca",
        objective="Reply with the single word: ready.",
        container=container,
        role="recon",
        timeout=180.0,
    )
)
print(f"  sdk {answer.sdk_version}   cli {answer.cli_version}")
print(f"  apiKeySource {answer.api_key_source}   stopped as {answer.stop_reason}")
raise SystemExit(0 if answer.api_key_source == "none" else 1)
CANARY
else
  SKIPPED+=("the canary — declined")
fi

finish
